---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder
spec:
  selector:
    matchLabels:
      app: adder
  template:
    metadata:
      labels:
        app: adder
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "adder"
        dapr.io/app-protocol: "http"
        dapr.io/app-port: "8080"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "error"
    spec:
      containers:
        - name: gateway
          image: kzmake/adder:latest
          command:
            - /gateway
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: adder-gateway-config
              prefix: GATEWAY
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 1
        - name: service
          image: kzmake/adder:latest
          command:
            - /service
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: adder-service-config
              prefix: SERVICE
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - name: grpc
              containerPort: 50051
            - name: health
              containerPort: 55051
          livenessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:55051"]
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:55051"]
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: adder
spec:
  type: ClusterIP
  selector:
    app: adder
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051
