version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "sh -c 'trap : SIGTERM SIGINT; sleep infinity & wait'"
    environment:
      KUBECONFIG: /go/src/app/.kube/config
    volumes:
      - .:/go/src/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
