// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/subtractor/v1/subtractor.proto

package subtractor

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperandOne float64 `protobuf:"fixed64,1,opt,name=operand_one,json=operandOne,proto3" json:"operand_one,omitempty"`
	OperandTwo float64 `protobuf:"fixed64,2,opt,name=operand_two,json=operandTwo,proto3" json:"operand_two,omitempty"`
}

func (x *SubRequest) Reset() {
	*x = SubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_subtractor_v1_subtractor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRequest) ProtoMessage() {}

func (x *SubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subtractor_v1_subtractor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRequest.ProtoReflect.Descriptor instead.
func (*SubRequest) Descriptor() ([]byte, []int) {
	return file_api_subtractor_v1_subtractor_proto_rawDescGZIP(), []int{0}
}

func (x *SubRequest) GetOperandOne() float64 {
	if x != nil {
		return x.OperandOne
	}
	return 0
}

func (x *SubRequest) GetOperandTwo() float64 {
	if x != nil {
		return x.OperandTwo
	}
	return 0
}

type Subresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float64 `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Subresponse) Reset() {
	*x = Subresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_subtractor_v1_subtractor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subresponse) ProtoMessage() {}

func (x *Subresponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_subtractor_v1_subtractor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subresponse.ProtoReflect.Descriptor instead.
func (*Subresponse) Descriptor() ([]byte, []int) {
	return file_api_subtractor_v1_subtractor_proto_rawDescGZIP(), []int{1}
}

func (x *Subresponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_api_subtractor_v1_subtractor_proto protoreflect.FileDescriptor

var file_api_subtractor_v1_subtractor_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0a,
	0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x74, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x54, 0x77, 0x6f, 0x22, 0x25, 0x0a, 0x0b,
	0x53, 0x75, 0x62, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x71, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x63, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x12, 0x24, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x75, 0x62, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x22, 0x04, 0x2f,
	0x73, 0x75, 0x62, 0x3a, 0x01, 0x2a, 0x42, 0x60, 0x5a, 0x5e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x7a, 0x6d, 0x61, 0x6b, 0x65, 0x2f, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x75,
	0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_subtractor_v1_subtractor_proto_rawDescOnce sync.Once
	file_api_subtractor_v1_subtractor_proto_rawDescData = file_api_subtractor_v1_subtractor_proto_rawDesc
)

func file_api_subtractor_v1_subtractor_proto_rawDescGZIP() []byte {
	file_api_subtractor_v1_subtractor_proto_rawDescOnce.Do(func() {
		file_api_subtractor_v1_subtractor_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_subtractor_v1_subtractor_proto_rawDescData)
	})
	return file_api_subtractor_v1_subtractor_proto_rawDescData
}

var file_api_subtractor_v1_subtractor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_subtractor_v1_subtractor_proto_goTypes = []interface{}{
	(*SubRequest)(nil),  // 0: calculator.subtractor.v1.SubRequest
	(*Subresponse)(nil), // 1: calculator.subtractor.v1.Subresponse
}
var file_api_subtractor_v1_subtractor_proto_depIdxs = []int32{
	0, // 0: calculator.subtractor.v1.Subtractor.Sub:input_type -> calculator.subtractor.v1.SubRequest
	1, // 1: calculator.subtractor.v1.Subtractor.Sub:output_type -> calculator.subtractor.v1.Subresponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_subtractor_v1_subtractor_proto_init() }
func file_api_subtractor_v1_subtractor_proto_init() {
	if File_api_subtractor_v1_subtractor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_subtractor_v1_subtractor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_subtractor_v1_subtractor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_subtractor_v1_subtractor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_subtractor_v1_subtractor_proto_goTypes,
		DependencyIndexes: file_api_subtractor_v1_subtractor_proto_depIdxs,
		MessageInfos:      file_api_subtractor_v1_subtractor_proto_msgTypes,
	}.Build()
	File_api_subtractor_v1_subtractor_proto = out.File
	file_api_subtractor_v1_subtractor_proto_rawDesc = nil
	file_api_subtractor_v1_subtractor_proto_goTypes = nil
	file_api_subtractor_v1_subtractor_proto_depIdxs = nil
}
